import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Othoba Mart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <article>
       <section>
         <div>
           <p className='text-center text-3xl bg-red-100'>This is Head of Home Page</p>
         </div>
       </section>
     </article>
    </div>
  )
}
